### ISSUE TITLE
Bomb out during sync from bad UTF tag

### ISSUE THREAD

**Issue by redshodan** [nicfit/MishMash#194] opened 2017-09-24 18:13 UTC
```
Adding track: /data/home/baron-data/music/Foreign Born/holy.mp3
2017-09-24 12:07:56,065 ERROR [mishmash][MainThread] 'utf-8' codec can't encode character '\udce9' in position 104: surrogates not allowed
Traceback (most recent call last):
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/MishMash-0.3b4-py3.6.egg/mishmash/__main__.py", line 53, in main
    retval = args.command_func(args, args.config) or 0
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/MishMash-0.3b4-py3.6.egg/mishmash/core.py", line 20, in run
    retval = super().run(args)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/nicfit.py-0.6.5-py3.6.egg/nicfit/command.py", line 62, in run
    return self._run()
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/MishMash-0.3b4-py3.6.egg/mishmash/commands/sync/sync.py", line 458, in _run
    result = _syncLib(lib)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/MishMash-0.3b4-py3.6.egg/mishmash/commands/sync/sync.py", line 451, in _syncLib
    return eyed3_main(args, None)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/utils/__init__.py", line 103, in walk
    handler.handleFile(f)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/plugins/__init__.py", line 172, in handleFile
    self.audio_file = core.load(f, *args, **kwargs)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/core.py", line 72, in load
    mtype = guessMimetype(path)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/utils/__init__.py", line 57, in guessMimetype
    mime = _mime_types.guess_type(filename)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/utils/__init__.py", line 46, in guess_type
    return self.from_file(filename)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/python_magic-0.4.13-py3.6.egg/magic.py", line 85, in from_file
    return maybe_decode(magic_file(self.cookie, filename))
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/python_magic-0.4.13-py3.6.egg/magic.py", line 242, in magic_file
    return _magic_file(cookie, coerce_filename(filename))
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/python_magic-0.4.13-py3.6.egg/magic.py", line 216, in coerce_filename
    return filename.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 104: surrogates not allowed
General error:
Traceback (most recent call last):
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/MishMash-0.3b4-py3.6.egg/mishmash/__main__.py", line 53, in main
    retval = args.command_func(args, args.config) or 0
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/MishMash-0.3b4-py3.6.egg/mishmash/core.py", line 20, in run
    retval = super().run(args)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/nicfit.py-0.6.5-py3.6.egg/nicfit/command.py", line 62, in run
    return self._run()
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/MishMash-0.3b4-py3.6.egg/mishmash/commands/sync/sync.py", line 458, in _run
    result = _syncLib(lib)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/MishMash-0.3b4-py3.6.egg/mishmash/commands/sync/sync.py", line 451, in _syncLib
    return eyed3_main(args, None)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/main.py", line 50, in main
    fs_encoding=args.fs_encoding)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/utils/__init__.py", line 103, in walk
    handler.handleFile(f)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/plugins/__init__.py", line 172, in handleFile
    self.audio_file = core.load(f, *args, **kwargs)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/core.py", line 72, in load
    mtype = guessMimetype(path)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/utils/__init__.py", line 57, in guessMimetype
    mime = _mime_types.guess_type(filename)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/eyeD3-0.8.2-py3.6.egg/eyed3/utils/__init__.py", line 46, in guess_type
    return self.from_file(filename)
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/python_magic-0.4.13-py3.6.egg/magic.py", line 85, in from_file
    return maybe_decode(magic_file(self.cookie, filename))
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/python_magic-0.4.13-py3.6.egg/magic.py", line 242, in magic_file
    return _magic_file(cookie, coerce_filename(filename))
  File "/home/baron/src/unsonic/build/venv/lib/python3.6/site-packages/python_magic-0.4.13-py3.6.egg/magic.py", line 216, in coerce_filename
    return filename.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 104: surrogates not allowed
2017-09-24 12:07:56,072 DEBUG [unsonic][MainThread] Application._atexit
make: *** [Makefile:63: build/development.sqlite] Error 2
```

**Comment by redshodan** [comment] 2017-09-24 18:14
When running eyeD3 against the file directly:

baron@dib ~/src/unsonic $ eyeD3 "/data/home/baron-data/music/Foreign Born/holy.mp3"
/data/home/baron-data/music/Foreign Born/holy.mp3                  [ 6.25 MB ]
-------------------------------------------------------------------------------
Time: 04:33	MPEG1, Layer III	[ 192 kb/s @ 44100 Hz - Stereo ]
-------------------------------------------------------------------------------
ID3 v2.2:
title: holy splinter
artist: Foreign Born
album: Demo
album artist: None
track: 		
Comment: [Description: iTunNORM] [Lang: eng]
 0000056D 000005A8 00002433 00002B90 000170AC 000206AC 000086A9 0000886D 00030AC6 0003BCBC
-------------------------------------------------------------------------------

**Comment by nicfit** [comment] 2017-09-27 01:34
The file holy.mp3 has nothing to do this this, run eyeD3 over the collection and you'll find an incorrectly encoded filename. I actually reproduced on a directory of crap mp3s I have sitting around. Your stack trace is similar to [this](https://stackoverflow.com/questions/27366479/python-3-os-walk-file-paths-unicodeencodeerror-utf-8-codec-cant-encode-s).  Patching magic-py moves the problem to eyeD3 ``printMsg`` due to [this](https://bugs.python.org/issue13717). 

See:
https://github.com/ahupp/python-magic/pull/144
https://github.com/nicfit/eyeD3/commit/99a576a29cc8b16d8a6d27eccb202560f61821b8

**Comment by nicfit** [comment] 2017-11-05 02:17
On of these is fixed by https://github.com/nicfit/eyeD3/commit/7ffef222076c38823291eda685ed7b3e16a34f6a

**Comment by nicfit** [comment] 2017-11-05 04:50
Both now fixed

**Closed by nicfit** 2017-11-05 04:50 UTC
